---
- name: OS and Security Patch Info Report
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    #Last Update Time

    - name: Get last update timestamp (Ubuntu/Debian)
      ansible.builtin.shell: stat -c %y /var/lib/apt/periodic/update-success-stamp
      register: last_update_debian
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Debian"
      tags: last_update

    

    #Pending OS Updates

    - name: List pending OS updates (Ubuntu/Debian)
      ansible.builtin.shell: apt list --upgradable 2>/dev/null | tail -n +2
      register: os_updates_debian
      changed_when: false
      when: ansible_os_family == "Debian"
      tags: os_updates

    

    #Pending Security Updates

    - name: List security updates (Ubuntu/Debian)
      ansible.builtin.shell: apt list --upgradable 2>/dev/null | grep -i security
      register: security_updates_debian
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Debian"
      tags: security_updates

    

    #Display Results

    - name: Show last update time (Ubuntu/Debian)
      ansible.builtin.debug:
        msg: "Last update was on {{ last_update_debian.stdout }}"
      when: ansible_os_family == "Debian"
      tags: last_update

    
    - name: Show pending OS updates (Ubuntu/Debian)
      ansible.builtin.debug:
        var: os_updates_debian.stdout_lines
      when: ansible_os_family == "Debian"
      tags: os_updates

    

    - name: Show pending security updates (Ubuntu/Debian)
      ansible.builtin.debug:
        var: security_updates_debian.stdout_lines
      when: ansible_os_family == "Debian"
      tags: security_updates

    
